# COMPUTED VALUES:
# annotations: {}
# config: null
# count: 1
# elasticsearchRef:
#   name: eck-elasticsearch
#   namespace: eck-operator
# ingress:
#   annotations: {}
#   enabled: false
#   hosts:
#   - host: chart-example.local
#     path: /
#   labels: {}
#   pathType: Prefix
# spec:
#   http:
#     tls:
#       selfSignedCertificate:
#         disabled: true
# labels: {}
# monitoring: {}
# secureSettings: []
# version: 9.2.0
# readinessProbe:
#   failureThreshold: 3
#   initialDelaySeconds: 120
#   periodSeconds: 60
#   successThreshold: 3
#   timeoutSeconds: 5
