apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://chartmuseum.github.io/charts
    chart: chartmuseum
    targetRevision: 3.10.1
    helm:
      values: |
        env:
          open:
            DISABLE_API: false
        service:
          type: NodePort
          nodePort: 30080
          port: 8080

  destination:
    namespace: chartmuseum
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
