apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-ap-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
    chart: stage-ap-chart
    targetRevision: 0.1.0

  destination:
    namespace: stage
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
